---PRIMARY KEY CONSTRAINTS

ALTER TABLE PATIENTS ADD PRIMARY KEY (PATIENT_ID);
ALTER TABLE HOSPITALS ADD PRIMARY KEY (HOSPITAL_ID);
ALTER TABLE EMPLOYEES ADD PRIMARY KEY (EMPLOYEE_ID);
ALTER TABLE VISITS ADD PRIMARY KEY (VISIT_ID);
ALTER TABLE MEDICATIONS ADD PRIMARY KEY (MEDICATION_ID);

---FK CONSTRAINTS

ALTER TABLE VISIT ADD CONSTRAINTS FK_1 FOREIGN KEY (PATIENT_ID)REFERENCES PATIENTS (PATIENT_ID);
ALTER TABLE VISITS ADD CONSTRAINTS FK_2 FOREIGN KEY (EMPLOYEE_ID)REFERENCES EMPLOYEES (EMPLOYEE_ID);
ALTER TABLE EMPLOYEES ADD CONSTRAINTS FK_3 FOREIGN KEY (HOSPITAL_ID)REFERENCES HOSPITAL(HOSPITAL_ID);
ALTER TABLE PRESCRIPTIONS ADD CONSTRAINTS FK_4 FOREIGN KEY (MEDICATION_ID)REFERENCE MEDICATIONS(MEDICATION_ID);

 